version: "3"

services:
  web:
    build: nodejs
    command: sh -c "/wait && node index.js"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=60
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 80:3000
      - 443:443
    depends_on:
      - db
 
  db:
    image: dolthub/dolt-sql-server
    ports:
      - 3306
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    
